/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Birds;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.util.Random;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Muhaimenur
 */
public class BirdSelect extends javax.swing.JFrame {

    ImageIcon im1 = new ImageIcon("cartoon/c1.jpg");
    ImageIcon im2 = new ImageIcon("cartoon/c2.jpg");
    ImageIcon im3 = new ImageIcon("cartoon/c3.jpg");
    ImageIcon im4 = new ImageIcon("cartoon/c4.jpg");
    ImageIcon im5 = new ImageIcon("cartoon/c5.jpg");
    ImageIcon im6 = new ImageIcon("cartoon/c6.jpg");
    ImageIcon im7 = new ImageIcon("cartoon/c7.jpg");
    ImageIcon im8 = new ImageIcon("cartoon/c8.jpg");
    ImageIcon im9 = new ImageIcon("cartoon/c9.jpg");
    ImageIcon im10 = new ImageIcon("cartoon/c10.jpg");
    ImageIcon im11 = new ImageIcon("cartoon/c11.jpg");
    ImageIcon im12 = new ImageIcon("cartoon/c12.jpg");
    ImageIcon im13 = new ImageIcon("cartoon/c13.jpg");
    ImageIcon im14 = new ImageIcon("cartoon/c14.jpg");
    ImageIcon im15 = new ImageIcon("cartoon/c15.jpg");
    ImageIcon im16 = new ImageIcon("cartoon/c16.jpg");
    ImageIcon im17 = new ImageIcon("cartoon/c17.jpg");
    ImageIcon im18 = new ImageIcon("cartoon/c18.jpg");

    ImageIcon imd1 = new ImageIcon("cartoon/id1.jpg");
    ImageIcon imd2 = new ImageIcon("cartoon/id2.jpg");
    ImageIcon imd3 = new ImageIcon("cartoon/id3.jpg");
    ImageIcon imd4 = new ImageIcon("cartoon/id4.jpg");
    ImageIcon imd5 = new ImageIcon("cartoon/id5.jpg");
    ImageIcon imd6 = new ImageIcon("cartoon/id6.jpg");
    ImageIcon imd7 = new ImageIcon("cartoon/id7.jpg");
    ImageIcon imd8 = new ImageIcon("cartoon/id8.jpg");
    ImageIcon imd9 = new ImageIcon("cartoon/id9.jpg");
    ImageIcon imd10 = new ImageIcon("cartoon/id10.jpg");
    ImageIcon imd11 = new ImageIcon("cartoon/id11.jpg");
    ImageIcon imd12 = new ImageIcon("cartoon/id12.jpg");

    private long start;
    private Timer timer;
    private boolean chromeShown;

    public BirdSelect() {

        super("RIO BIRDS");

        setSize(600, 600);

        // setBackground(Color.BLACK);
        // setForeground(Color.BLUE);
        setDefaultCloseOperation(EXIT_ON_CLOSE);

        setVisible(true);

        setResizable(false);

        setLocationRelativeTo(null);

        initComponents();

        jTextField1.setText("  000 ");

        jTextField2.setText(String.format("  %03d ", a));

        jTextField4.setText(" 01 : 00 ");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 490));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Total Score:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(380, 100, 108, 33);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("High Score:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(380, 150, 108, 32);

        jTextField1.setBackground(java.awt.Color.yellow);
        jTextField1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(500, 100, 90, 35);

        jTextField2.setBackground(java.awt.Color.orange);
        jTextField2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(500, 150, 90, 35);

        jLabel3.setBackground(new java.awt.Color(255, 255, 51));
        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setText("TIME:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(400, 20, 90, 36);

        jButton10.setBackground(java.awt.Color.green);
        jButton10.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton10.setForeground(new java.awt.Color(51, 51, 255));
        jButton10.setText("CREDIT");
        jButton10.setBorder(new javax.swing.border.MatteBorder(null));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(470, 280, 120, 43);

        jButton11.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton11.setText("INSTRUCTION");
        jButton11.setBorder(new javax.swing.border.MatteBorder(null));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(460, 400, 130, 44);

        jButton12.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton12.setText("START GAME");
        jButton12.setBorder(new javax.swing.border.MatteBorder(null));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(230, 400, 140, 44);

        jButton13.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton13.setText("NEW GAME");
        jButton13.setBorder(new javax.swing.border.MatteBorder(null));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(10, 400, 130, 44);

        jTextField4.setBackground(new java.awt.Color(51, 255, 204));
        jTextField4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 0, 204));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(500, 20, 90, 36);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 255));
        jButton1.setText("Rio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 80, 116, 81);

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 204, 255));
        jButton2.setText("Rio");
        getContentPane().add(jButton2);
        jButton2.setBounds(130, 80, 115, 81);

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 204, 255));
        jButton3.setText("Rio");
        getContentPane().add(jButton3);
        jButton3.setBounds(250, 80, 115, 81);

        jButton4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 204, 255));
        jButton4.setText("Rio");
        getContentPane().add(jButton4);
        jButton4.setBounds(10, 170, 116, 80);

        jButton5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 204, 255));
        jButton5.setText("Rio");
        getContentPane().add(jButton5);
        jButton5.setBounds(130, 170, 115, 80);

        jButton6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 204, 204));
        jButton6.setText("Rio");
        getContentPane().add(jButton6);
        jButton6.setBounds(250, 170, 115, 80);

        jButton7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 204, 204));
        jButton7.setText("Rio");
        getContentPane().add(jButton7);
        jButton7.setBounds(10, 260, 116, 80);

        jButton8.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 204, 204));
        jButton8.setText("Rio");
        getContentPane().add(jButton8);
        jButton8.setBounds(130, 260, 115, 80);

        jButton9.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 204, 204));
        jButton9.setText("Rio");
        getContentPane().add(jButton9);
        jButton9.setBounds(250, 260, 115, 80);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rio 8.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 600, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int w, r, g;
    int p, q, i, l;
    int n, m, k;

    int x;
    int d = 0;

    int a = 0;

    int h = 0;

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed

        function();

        //do something
        playSound2("a/audio.wav");

        if (h == 0) {

            //playSound("a/Rio.wav");

        }

        h++;

    }

    private void function() {

        x = 0;

        w = 60;

        jButton12.setEnabled(false);

        timer = new Timer(1000, new ActionListener() {
            //  @Override

            public void actionPerformed(ActionEvent e) {

                jTextField4.setText(String.format(" 00 : %02d ", w));

                jTextField1.setText(String.format("  %03d ", x));

                jTextField2.setText(String.format("  %03d ", a));

                if (x > a) {
                    a = x;

                }

                w--;

                if (w == 00) {

                    jTextField4.setText(" 01 : 00 ");

                    jButton12.setEnabled(true);

                    jButton1.setIcon(null);
                    chromeShown = true;

                    jButton2.setIcon(null);
                    chromeShown = true;

                    jButton3.setIcon(null);
                    chromeShown = true;
                    jButton4.setIcon(null);
                    chromeShown = true;
                    jButton5.setIcon(null);
                    chromeShown = true;

                    jButton6.setIcon(null);
                    chromeShown = true;
                    jButton7.setIcon(null);
                    chromeShown = true;
                    jButton8.setIcon(null);
                    chromeShown = true;
                    jButton9.setIcon(null);
                    chromeShown = true;

                }

                if (w == 00) {

                    timer.stop();

                }
                if (chromeShown) {

                    jButton1.setIcon(null);
                    chromeShown = false;

                    jButton2.setIcon(null);
                    chromeShown = false;

                    jButton3.setIcon(null);
                    chromeShown = false;
                    jButton4.setIcon(null);
                    chromeShown = false;
                    jButton5.setIcon(null);
                    chromeShown = false;

                    jButton6.setIcon(null);
                    chromeShown = false;
                    jButton7.setIcon(null);
                    chromeShown = false;
                    jButton8.setIcon(null);
                    chromeShown = false;
                    jButton9.setIcon(null);
                    chromeShown = false;

                } else {
                    Random rand = new Random();

                    n = rand.nextInt(9) + 1;

                    Random rand1 = new Random();
                    m = rand.nextInt(9) + 1;

                    Random rand2 = new Random();
                    k = rand.nextInt(9) + 1;

                    if ((m == n) || (n == k) || (m == k)) {
                        if (n < 9) {
                            m = n + 1;
                            if (n < 8) {
                                k = m + 2;

                            }
                        }
                    }

                    if (n == 1) {

                        jButton1.setIcon(im1);

                        chromeShown = true;

                        jButton1.addActionListener(new ActionListener() {
                            public void actionPerformed(ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                            }

                            private void jButton1ActionPerformed(ActionEvent evt) {
                                x = x + 5;

                            }

                        });

                    }

                    if (m == 1) {

                        jButton5.setIcon(im3);

                        chromeShown = true;
                        jButton5.addActionListener(new ActionListener() {
                            public void actionPerformed(ActionEvent evt) {
                                jButton5ActionPerformed(evt);
                            }

                            private void jButton5ActionPerformed(ActionEvent evt) {
                                x = x + 5;

                            }

                        });

                    }
                    if (k == 1) {

                        jButton3.setIcon(imd2);
                        chromeShown = true;
                        jButton3.addActionListener(new ActionListener() {
                            public void actionPerformed(ActionEvent evt) {
                                jButton3ActionPerformed(evt);
                            }

                            private void jButton3ActionPerformed(ActionEvent evt) {
                                x = x - 5;
                            }

                        });

                    }


                    if (n == 2) {

                        jButton2.setIcon(im6);
                        chromeShown = true;
                        jButton2.addActionListener(new ActionListener() {
                            public void actionPerformed(ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                            }

                            private void jButton2ActionPerformed(ActionEvent evt) {
                                x = x + 5;
                            }

                        });

                    }

                    if (m == 2) {

                        jButton4.setIcon(im6);
                        chromeShown = true;
                        jButton4.addActionListener(new ActionListener() {
                            public void actionPerformed(ActionEvent evt) {
                                jButton4ActionPerformed(evt);
                            }

                            private void jButton4ActionPerformed(ActionEvent evt) {
                                x = x + 5;
                            }

                        });

                    }

                    if (k == 2) {

                        jButton7.setIcon(imd1);
                        chromeShown = true;
                        jButton7.addActionListener(new ActionListener() {
                            public void actionPerformed(ActionEvent evt) {
                                jButton7ActionPerformed(evt);
                            }

                            private void jButton7ActionPerformed(ActionEvent evt) {
                                x = x - 5;
                            }

                        });

                    }


                    if (m == 3) {

                        jButton5.setIcon(im9);
                        chromeShown = true;
                        jButton5.addActionListener(new ActionListener() {
                            public void actionPerformed(ActionEvent evt) {
                                jButton5ActionPerformed(evt);
                            }

                            private void jButton5ActionPerformed(ActionEvent evt) {
                                x = x + 5;
                            }

                        });

                    }

                    if (m == 3) {

                        jButton8.setIcon(im8);
                        chromeShown = true;
                        jButton8.addActionListener(new ActionListener() {
                            public void actionPerformed(ActionEvent evt) {
                                jButton8ActionPerformed(evt);
                            }

                            private void jButton8ActionPerformed(ActionEvent evt) {
                                x = x + 5;
                            }

                        });

                    }

                    if (k == 3) {

                        jButton2.setIcon(imd4);
                        chromeShown = true;
                        jButton2.addActionListener(new ActionListener() {
                            public void actionPerformed(ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                            }

                            private void jButton2ActionPerformed(ActionEvent evt) {
                                x = x + 5;
                            }

                        });

                    }


                    if (m == 4) {

                        jButton6.setIcon(im6);
                        chromeShown = true;
                        jButton6.addActionListener(new ActionListener() {
                            public void actionPerformed(ActionEvent evt) {
                                jButton6ActionPerformed(evt);
                            }

                            private void jButton6ActionPerformed(ActionEvent evt) {
                                x = x + 5;
                            }

                        });

                    }

                    if (m == 4) {

                        jButton4.setIcon(im16);
                        chromeShown = true;
                        jButton4.addActionListener(new ActionListener() {
                            public void actionPerformed(ActionEvent evt) {
                                jButton4ActionPerformed(evt);
                            }

                            private void jButton4ActionPerformed(ActionEvent evt) {
                                x = x + 5;
                            }

                        });

                    }

                    if (k == 4) {

                        jButton1.setIcon(imd3);
                        chromeShown = true;
                        jButton1.addActionListener(new ActionListener() {
                            public void actionPerformed(ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                            }

                            private void jButton1ActionPerformed(ActionEvent evt) {
                                x = x - 5;
                            }

                        });

                    }

                    if (n == 5) {

                        jButton5.setIcon(im9);
                        chromeShown = true;

                        jButton5.addActionListener(new ActionListener() {
                            public void actionPerformed(ActionEvent evt) {
                                jButton5ActionPerformed(evt);
                            }

                            private void jButton5ActionPerformed(ActionEvent evt) {
                                x = x + 5;
                            }

                        });

                    }

                    if (m == 5) {

                        jButton6.setIcon(im11);
                        chromeShown = true;

                        jButton6.addActionListener(new ActionListener() {
                            public void actionPerformed(ActionEvent evt) {
                                jButton6ActionPerformed(evt);
                            }

                            private void jButton6ActionPerformed(ActionEvent evt) {
                                x = x + 5;
                            }

                        });

                    }

                    if (k == 5) {

                        jButton1.setIcon(im13);
                        chromeShown = true;

                        jButton1.addActionListener(new ActionListener() {
                            public void actionPerformed(ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                            }

                            private void jButton1ActionPerformed(ActionEvent evt) {
                                x = x + 5;
                            }

                        });

                    }


                    if (n == 6) {

                        jButton8.setIcon(im6);
                        chromeShown = true;

                        jButton8.addActionListener(new ActionListener() {
                            public void actionPerformed(ActionEvent evt) {
                                jButton8ActionPerformed(evt);
                            }

                            private void jButton8ActionPerformed(ActionEvent evt) {
                                x = x + 5;
                            }

                        });

                    }

                    if (m == 6) {

                        jButton4.setIcon(im3);
                        chromeShown = true;

                        jButton4.addActionListener(new ActionListener() {
                            public void actionPerformed(ActionEvent evt) {
                                jButton4ActionPerformed(evt);
                            }

                            private void jButton4ActionPerformed(ActionEvent evt) {
                                x = x + 5;
                            }

                        });

                    }
                    if (k == 6) {

                        jButton2.setIcon(imd7);
                        chromeShown = true;

                        jButton2.addActionListener(new ActionListener() {
                            public void actionPerformed(ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                            }

                            private void jButton2ActionPerformed(ActionEvent evt) {
                                x = x - 5;
                            }

                        });

                    }


                    if (n == 7) {

                        jButton3.setIcon(im13);
                        chromeShown = true;

                        jButton3.addActionListener(new ActionListener() {
                            public void actionPerformed(ActionEvent evt) {
                                jButton3ActionPerformed(evt);
                            }

                            private void jButton3ActionPerformed(ActionEvent evt) {
                                x = x + 5;
                            }

                        });

                    }
                    if (m == 7) {

                        jButton6.setIcon(im16);
                        chromeShown = true;

                        jButton6.addActionListener(new ActionListener() {
                            public void actionPerformed(ActionEvent evt) {
                                jButton6ActionPerformed(evt);
                            }

                            private void jButton6ActionPerformed(ActionEvent evt) {
                                x = x + 5;
                            }

                        });

                    }

                    if (k == 7) {

                        jButton1.setIcon(imd3);
                        chromeShown = true;

                        jButton1.addActionListener(new ActionListener() {
                            public void actionPerformed(ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                            }

                            private void jButton1ActionPerformed(ActionEvent evt) {
                                x = x - 5;
                            }

                        });

                    }


                    if (n == 8) {
                        jButton9.setIcon(im17);
                        chromeShown = true;

                        jButton9.addActionListener(new ActionListener() {
                            public void actionPerformed(ActionEvent evt) {
                                jButton9ActionPerformed(evt);
                            }

                            private void jButton9ActionPerformed(ActionEvent evt) {
                                x = x + 5;
                            }

                        });
                    }

                    if (m == 8) {
                        jButton5.setIcon(im14);
                        chromeShown = true;

                        jButton5.addActionListener(new ActionListener() {
                            public void actionPerformed(ActionEvent evt) {
                                jButton5ActionPerformed(evt);
                            }

                            private void jButton5ActionPerformed(ActionEvent evt) {
                                x = x + 5;
                            }

                        });
                    }
                    if (k == 8) {
                        jButton1.setIcon(imd5);
                        chromeShown = true;
                        jButton1.addActionListener(new ActionListener() {
                            public void actionPerformed(ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                            }

                            private void jButton1ActionPerformed(ActionEvent evt) {
                                x = x - 5;
                            }

                        });

                    }

 
                    if (n == 9) {
                        jButton7.setIcon(im7);
                        chromeShown = true;

                        jButton7.addActionListener(new ActionListener() {
                            public void actionPerformed(ActionEvent evt) {
                                jButton7ActionPerformed(evt);
                            }

                            private void jButton7ActionPerformed(ActionEvent evt) {
                                x = x + 5;
                            }

                        });
                    }
                    if (m == 9) {
                        jButton1.setIcon(im15);
                        chromeShown = true;
                        jButton1.addActionListener(new ActionListener() {
                            public void actionPerformed(ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                            }

                            private void jButton1ActionPerformed(ActionEvent evt) {
                                x = x + 5;
                            }

                        });

                    }

                    if (k == 9) {
                        jButton5.setIcon(imd11);
                        chromeShown = true;
                        jButton5.addActionListener(new ActionListener() {
                            public void actionPerformed(ActionEvent evt) {
                                jButton5ActionPerformed(evt);
                            }

                            private void jButton5ActionPerformed(ActionEvent evt) {
                                x = x - 5;
                            }

                        });

                    }

                }

            }

        });

        jTextField4.setText(" 01 : 00 ");

        jTextField1.setText("  000 ");

        jTextField2.setText(String.format("  %03d ", a));

        timer.start();

        // this.getContentPane().add(panel);
        this.setVisible(true);

        start = System.currentTimeMillis();
//

    }

   /* public void playSound(String soundName) {
        try {

            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File(soundName).getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();

        } catch (Exception ex) {
            System.out.println("Error with playing sound.");
            ex.printStackTrace();
        }
    }*/

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BirdSelect.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BirdSelect.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BirdSelect.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BirdSelect.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                new BirdSelect().setVisible(true);

            }

        });
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:

        playSound2("a/audio.wav");

        JOptionPane.showMessageDialog(null, "\n NAME:-  Md. Muhaimenur Rahman ,  REG:- 2012331549");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:

        playSound2("a/audio.wav");

        JOptionPane.showMessageDialog(null, "   \n   1. Click the birds and get more score . \n\n    2. Try again for set score . \n\n  3. Time is limit .", " ***  < 'INSTRUCTION' > *** ", JOptionPane.PLAIN_MESSAGE, im3);


    }//GEN-LAST:event_jButton11ActionPerformed

    public void playSound1(String soundName) {

        try {

            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File(soundName).getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();

        } catch (Exception ex) {
            System.out.println("Error with playing sound.");
            ex.printStackTrace();

        }
    }

    public void playSound2(String soundName) {

        try {

            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File(soundName).getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();

        } catch (Exception ex) {
            System.out.println("Error with playing sound.");
            ex.printStackTrace();

        }
    }


    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed

        // TODO add your handling code here:
        playSound1("a/audio1.wav");

        timer.stop();

        jButton12.setEnabled(true);

        jTextField4.setText(" 01 : 00 ");

        jTextField1.setText("  000 ");

        jTextField2.setText(String.format("  %03d ", a));

        jButton1.setIcon(null);
        chromeShown = true;

        jButton2.setIcon(null);
        chromeShown = true;

        jButton3.setIcon(null);
        chromeShown = true;

        jButton4.setIcon(null);
        chromeShown = true;

        jButton5.setIcon(null);
        chromeShown = true;

        jButton6.setIcon(null);
        chromeShown = true;

        jButton7.setIcon(null);
        chromeShown = true;

        jButton8.setIcon(null);
        chromeShown = true;

        jButton9.setIcon(null);
        chromeShown = true;


    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

}
